# Generated by Django 5.2 on 2025-04-18 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('REACHED_OUT', 'Reached Out')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
